/* **************************************************************************
 * E:\delivery\Dev\wix36_public\inc\wixver.h - version information for project
 *
 * 2012.4.3 - generated by build system.
 * **************************************************************************/

#ifndef _VERSION_FILE_H_
#define _VERSION_FILE_H_

#define szVerMajorMinor "3.6"
#define szVerMajorMinorBuild "3.6.2803.0"
#define rmj	3
#define rmm	6
#define rup	2803
#define szVerName	"Official Release"

#endif // _VERSION_FILE_H_
