using System.Reflection;

// Generated by build system.
//
// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version
//      Build Number
//      Revision
//

[assembly: AssemblyVersion("3.0.0.0")]
[assembly: AssemblyFileVersion("3.6.2803.0")]
